jobGroups:

- name: discovery
  testInfraJobSpec:
    targetFile: kubeadm-kinder-discovery.yaml
    template: ./templates/testinfra/kubeadm-kinder-discovery.yaml
  kinderWorkflowSpec:
    targetFile: discovery-{{ .KubernetesVersion }}.yaml
    template: ./templates/workflows/discovery.yaml
    additionalFiles:
    - ./templates/workflows/discovery-tasks.yaml
  jobs:
  - kubernetesVersion: latest
  - kubernetesVersion: 0
  - kubernetesVersion: -1
  - kubernetesVersion: -2
  - kubernetesVersion: -3

- name: external-ca
  testInfraJobSpec:
    targetFile: kubeadm-kinder-external-ca.yaml
    template: ./templates/testinfra/kubeadm-kinder-external-ca.yaml
  kinderWorkflowSpec:
    targetFile: external-ca-{{ .KubernetesVersion }}.yaml
    template: ./templates/workflows/external-ca.yaml
    additionalFiles:
    - ./templates/workflows/external-ca-tasks.yaml
  jobs:
  - kubernetesVersion: latest
  - kubernetesVersion: 0
  - kubernetesVersion: -1
  - kubernetesVersion: -2
  - kubernetesVersion: -3

- name: external-etcd
  testInfraJobSpec:
    targetFile: kubeadm-kinder-external-etcd.yaml
    template: ./templates/testinfra/kubeadm-kinder-external-etcd.yaml
  kinderWorkflowSpec:
    targetFile: external-etcd-{{ .KubernetesVersion }}.yaml
    template: ./templates/workflows/external-etcd.yaml
    additionalFiles:
    - ./templates/workflows/external-etcd-tasks.yaml
  jobs:
  - kubernetesVersion: latest
  - kubernetesVersion: 0
  - kubernetesVersion: -1
  - kubernetesVersion: -2
  - kubernetesVersion: -3

- name: patches
  minimumKubernetesVersion: v1.19.0
  testInfraJobSpec:
    targetFile: kubeadm-kinder-patches.yaml
    template: ./templates/testinfra/kubeadm-kinder-patches.yaml
  kinderWorkflowSpec:
    targetFile: patches-{{ .KubernetesVersion }}.yaml
    template: ./templates/workflows/patches.yaml
    additionalFiles:
    - ./templates/workflows/patches-tasks.yaml
  jobs:
  - kubernetesVersion: latest

- name: presubmit-upgrade-latest
  kinderWorkflowSpec:
    additionalFiles:
    - ./templates/workflows/presubmit-upgrade-latest.yaml

- name: skew-kubelet-x-on-y
  testInfraJobSpec:
    targetFile: kubeadm-kinder-kubelet-x-on-y.yaml
    template: ./templates/testinfra/kubeadm-kinder-kubelet-x-on-y.yaml
  kinderWorkflowSpec:
    targetFile: skew-kubelet-{{ .KubeletVersion }}-on-{{ .KubernetesVersion }}.yaml
    template: ./templates/workflows/skew-kubelet-x-on-y.yaml
    additionalFiles:
    - ./templates/workflows/skew-x-on-y-tasks.yaml
  jobs:
  - kubernetesVersion: latest
    kubeletVersion: 0
    skipVersions: [ +1 ]
  - kubernetesVersion: latest
    kubeletVersion: -1
    skipVersions: [ 0, +1 ]
  - kubernetesVersion: latest
    kubeletVersion: -2
    skipVersions: [ 0, +1, +2 ]
  - kubernetesVersion: 0
    kubeletVersion: -1
    skipVersions: [ 0 ]
  - kubernetesVersion: 0
    kubeletVersion: -2
    skipVersions: [ -1, 0 ]
  - kubernetesVersion: 0
    kubeletVersion: -3
    skipVersions: [ -2, -1, 0 ]
  - kubernetesVersion: -1
    kubeletVersion: -2
    skipVersions: [ -1 ]
  - kubernetesVersion: -1
    kubeletVersion: -3
    skipVersions: [ -2, -1 ]
  - kubernetesVersion: -2
    kubeletVersion: -3
    skipVersions: [ -2 ]

- name: skew-x-on-y
  testInfraJobSpec:
    targetFile: kubeadm-kinder-x-on-y.yaml
    template: ./templates/testinfra/kubeadm-kinder-x-on-y.yaml
  kinderWorkflowSpec:
    targetFile: skew-{{ .KubeadmVersion }}-on-{{ .KubernetesVersion }}.yaml
    template: ./templates/workflows/skew-x-on-y.yaml
    additionalFiles:
    - ./templates/workflows/skew-x-on-y-tasks.yaml
  jobs:
  - kubernetesVersion: 0
    kubeadmVersion: latest
  - kubernetesVersion: -1
    kubeadmVersion: 0
  - kubernetesVersion: -2
    kubeadmVersion: -1
  - kubernetesVersion: -3
    kubeadmVersion: -2

- name: upgrade
  testInfraJobSpec:
    targetFile: kubeadm-kinder-upgrade.yaml
    template: ./templates/testinfra/kubeadm-kinder-upgrade.yaml
  kinderWorkflowSpec:
    targetFile: upgrade-{{ .InitVersion }}-{{ .KubernetesVersion }}.yaml
    template: ./templates/workflows/upgrade.yaml
    additionalFiles:
    - ./templates/workflows/upgrade-tasks.yaml
  jobs:
  - initVersion: 0
    kubernetesVersion: latest
  - initVersion: -1
    kubernetesVersion: 0
  - initVersion: -2
    kubernetesVersion: -1
  - initVersion: -3
    kubernetesVersion: -2

- name: regular
  testInfraJobSpec:
    targetFile: kubeadm-kinder.yaml
    template: ./templates/testinfra/kubeadm-kinder.yaml
  kinderWorkflowSpec:
    targetFile: regular-{{ .KubernetesVersion }}.yaml
    template: ./templates/workflows/regular.yaml
    additionalFiles:
    - ./templates/workflows/regular-tasks.yaml
  jobs:
  - kubernetesVersion: latest
  - kubernetesVersion: 0
  - kubernetesVersion: -1
  - kubernetesVersion: -2
  - kubernetesVersion: -3

- name: upgrade-latest-no-addon-config-maps
  testInfraJobSpec:
    targetFile: kubeadm-kinder-addons.yaml
    template: ./templates/testinfra/kubeadm-kinder-addons.yaml
  kinderWorkflowSpec:
    targetFile: upgrade-latest-no-addon-config-maps.yaml
    additionalFiles:
    - ./templates/workflows/upgrade-latest-no-addon-config-maps.yaml
  jobs:
  - kubernetesVersion: latest

- name: rootless
  testInfraJobSpec:
    targetFile: kubeadm-kinder-rootless.yaml
    template: ./templates/testinfra/kubeadm-kinder-rootless.yaml
  kinderWorkflowSpec:
    targetFile: rootless-{{ .KubernetesVersion }}.yaml
    template: ./templates/workflows/rootless.yaml
    additionalFiles:
    - ./templates/workflows/rootless-tasks.yaml
  jobs:
  - kubernetesVersion: latest

- name: dryrun
  testInfraJobSpec:
    targetFile: kubeadm-kinder-dryrun.yaml
    template: ./templates/testinfra/kubeadm-kinder-dryrun.yaml
  kinderWorkflowSpec:
    targetFile: dryrun-{{ .KubernetesVersion }}.yaml
    template: ./templates/workflows/dryrun.yaml
    additionalFiles:
    - ./templates/workflows/dryrun-tasks.yaml
  jobs:
  - kubernetesVersion: latest
  - kubernetesVersion: 0
    upgradeVersion: latest
  - kubernetesVersion: -1
    upgradeVersion: 0
  - kubernetesVersion: -2
    upgradeVersion: -1
  - kubernetesVersion: -3
    upgradeVersion: -2

- name: learner-mode
  testInfraJobSpec:
    targetFile: kubeadm-kinder-learner-mode.yaml
    template: ./templates/testinfra/kubeadm-kinder-learner-mode.yaml
  kinderWorkflowSpec:
    targetFile: learner-mode-{{ .KubernetesVersion }}.yaml
    template: ./templates/workflows/learner-mode.yaml
    additionalFiles:
    - ./templates/workflows/learner-mode-tasks.yaml
  jobs:
  - kubernetesVersion: latest

- name: super-admin
  testInfraJobSpec:
    targetFile: kubeadm-kinder-super-admin.yaml
    template: ./templates/testinfra/kubeadm-kinder-super-admin.yaml
  kinderWorkflowSpec:
    targetFile: super-admin-{{ .KubernetesVersion }}.yaml
    template: ./templates/workflows/super-admin.yaml
    additionalFiles:
    - ./templates/workflows/super-admin-tasks.yaml
  jobs:
  - kubernetesVersion: latest

- name: wait-for-all-control-plane-components
  testInfraJobSpec:
    targetFile: kubeadm-kinder-wait-for-all-control-plane-components.yaml
    template: ./templates/testinfra/kubeadm-kinder-wait-for-all-control-plane-components.yaml
  kinderWorkflowSpec:
    targetFile: wait-for-all-control-plane-components-{{ .KubernetesVersion }}.yaml
    template: ./templates/workflows/wait-for-all-control-plane-components.yaml
    additionalFiles:
    - ./templates/workflows/wait-for-all-control-plane-components-tasks.yaml
  jobs:
  - kubernetesVersion: latest

- name: encryption-algorithm
  testInfraJobSpec:
    targetFile: kubeadm-kinder-encryption-algorithm.yaml
    template: ./templates/testinfra/kubeadm-kinder-encryption-algorithm.yaml
  kinderWorkflowSpec:
    targetFile: encryption-algorithm-{{ .KubernetesVersion }}.yaml
    template: ./templates/workflows/encryption-algorithm.yaml
    additionalFiles:
    - ./templates/workflows/encryption-algorithm-tasks.yaml
  jobs:
  - kubernetesVersion: latest

- name: control-plane-local-kubelet-mode
  testInfraJobSpec:
    targetFile: kubeadm-kinder-control-plane-local-kubelet-mode.yaml
    template: ./templates/testinfra/kubeadm-kinder-control-plane-local-kubelet-mode.yaml
  kinderWorkflowSpec:
    targetFile: control-plane-local-kubelet-mode-{{ .KubernetesVersion }}.yaml
    template: ./templates/workflows/control-plane-local-kubelet-mode.yaml
    additionalFiles:
    - ./templates/workflows/control-plane-local-kubelet-mode-tasks.yaml
  jobs:
  - kubernetesVersion: latest
