on: issue_comment
name: handle the /support command
permissions: {}
jobs:
  support_comment:
    permissions:
      issues: write

    runs-on: ubuntu-20.04
    steps:
      - name: check for the /support command
        id: command
        uses: xt0rted/slash-command-action@v2
        continue-on-error: true
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          command: support
          reaction: "false"
          allow-edits: "true"
          permission-level: admin
      - name: comment with support text
        if: steps.command.outputs.command-name
        uses: pacoxu/actions-comment-on-issue@1.0.3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: |
            Hello, @${{ github.event.issue.user.login }} :robot: :wave:

            You seem to have troubles using Kubernetes and kubeadm.
            Note that our issue trackers **should not** be used for providing support to users.
            There are special channels for that purpose.

            Please see:
            - https://github.com/kubernetes/kubeadm#support
      - name: add support label
        if: steps.command.outputs.command-name
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: kind/support
      - name: close issue
        if: steps.command.outputs.command-name
        uses: peter-evans/close-issue@v1
